/**
 * This file is generated by the rebirth-model compiler.
 *
 */
/* tslint:disable */

<% _.chain(type).filter(item => item.importType).forEach(item => {%>
import { <%=item.importType %> } from './<%=item.importType %>';
<%}).value()%>

export interface <%= name%> {
   <% _.forEach(type, item =>{%>
    <%=item.name %>: <%=item.type %>;
   <%})%>
}
